wutsi:
  application:
    gateway-url: https://wutsi-gateway-prod.herokuapp.com
    server-url: ${wutsi.application.gateway-url}/store
    asset-url: https://prod-wutsi.s3.amazonaws.com
  platform:
    security:
      api-key: ${API_KEY}
    storage:
      type: aws
      aws:
        bucket: prod-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
